language: node_js
node_js:
  - "14"

services:
  - docker

before_script:
  - npm install

script:
  - npm test

deploy:
  provider: script
  script: bash deploy.sh  # Agrega tu script de despliegue si es necesario
  on:
    branch: main
